import type { Metadata } from "next";

import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} data-qb-installed="true">
      <body>
        <div style={{
        backgroundImage: "url('https://img.freepik.com/foto-gratis/fondo-azul-degradado-lujo-abstracto-azul-oscuro-liso-banner-estudio-vineta-negra_1258-70937.jpg?t=st=1743379910~exp=1743383510~hmac=9e77e02e473d1dc1e469412a9603e790c1790c183c0ce3265da4e20fffcbd1e1&w=996')",
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        minHeight: '100vh', 
      }}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        </div>
      </body>
    </html>
  );
}